#写在前面：Lingfeng自用的单细胞流程，基于Seurat4.0，主打一个非结构个性化
#用到的包，没有的请用conda安装，不习惯使用conda的可以用BiocManager::install()安装
library("limma")
library("BiocManager")
library("Biobase")
library("BiocGenerics")
library("GEOquery")
library("Matrix")
library("dplyr")
library("cowplot")
library("stringr")
library("ggplot2")
library("Seurat")
library("multtest")
library("metap")
library(SingleR)
library(celldex)
library(viridisLite)
library(viridis)

#为方便使用，我直接列在了前面，请自行安装
